name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  texlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/@checkout@v3
    - name: Set up LaTeX linter
      uses: j2kun/chktex-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
